//! Label font catalog (allowlist) and helpers for CSS / `@font-face` loading.
//!
//! The slim catalog is generated by `tooling/fonts/sync.py` and embedded at
//! compile time. Binary `woff2` files live on the fonts CDN (see
//! `defaultBaseUrl`); they are never loaded unless a label uses that slug.

use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

use serde::Deserialize;

const CATALOG_JSON: &str = include_str!("../../../assets/label-fonts/catalog.json");

/// A single `@font-face` source file in the catalog.
#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct FontFaceFile {
    pub weight: u16,
    pub subset: String,
    pub path: String,
    pub unicode_range: String,
}

/// A font available for inline `[[font:…]]` directives.
#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct FontEntry {
    /// Slug used in directives (e.g. `roboto`, `heebo`).
    pub slug: String,
    pub label: String,
    pub family: Option<String>,
    pub category: String,
    pub scripts: Vec<String>,
    pub weights: Vec<u16>,
    pub license: Option<String>,
    /// CSS `font-family` value.
    pub css: String,
    #[serde(default)]
    pub faces: Vec<FontFaceFile>,
    pub preview: Option<String>,
    #[serde(default)]
    pub system: bool,
}

/// Slim font catalog shipped with the binary.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FontCatalog {
    pub version: String,
    pub default_base_url: String,
    pub fonts: Vec<FontEntry>,
}

/// Back-compat alias used by older docs/call sites.
pub type FontDef = FontEntry;

static CATALOG: OnceLock<FontCatalog> = OnceLock::new();
static BY_SLUG: OnceLock<HashMap<String, usize>> = OnceLock::new();

fn load_catalog() -> FontCatalog {
    serde_json::from_str(CATALOG_JSON).expect("embedded label-fonts catalog.json must parse")
}

/// Embedded font catalog (allowlist).
pub fn catalog() -> &'static FontCatalog {
    CATALOG.get_or_init(load_catalog)
}

fn slug_index() -> &'static HashMap<String, usize> {
    BY_SLUG.get_or_init(|| {
        catalog()
            .fonts
            .iter()
            .enumerate()
            .map(|(i, f)| (f.slug.to_ascii_lowercase(), i))
            .collect()
    })
}

/// All catalog entries (system + web fonts).
pub fn fonts() -> &'static [FontEntry] {
    &catalog().fonts
}

/// Look up a font by its directive slug (case-insensitive).
pub fn resolve_slug(slug: &str) -> Option<&'static FontEntry> {
    let key = slug.trim().to_ascii_lowercase();
    slug_index().get(&key).map(|&i| &catalog().fonts[i])
}

/// Default CDN base URL from the catalog (`https://fonts.lblprint.com/v1`).
pub fn default_font_assets_base_url() -> &'static str {
    catalog().default_base_url.as_str()
}

/// Resolve `FONT_ASSETS_BASE_URL` / `LBL_FONT_ASSETS_BASE_URL`, else catalog default.
pub fn font_assets_base_url_from_env() -> String {
    std::env::var("FONT_ASSETS_BASE_URL")
        .or_else(|_| std::env::var("LBL_FONT_ASSETS_BASE_URL"))
        .ok()
        .map(|s| s.trim().trim_end_matches('/').to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| default_font_assets_base_url().to_string())
}

/// Join base URL and relative object path.
pub fn font_asset_url(base: &str, rel_path: &str) -> String {
    let base = base.trim_end_matches('/');
    let rel = rel_path.trim_start_matches('/');
    format!("{base}/{rel}")
}

/// Collect distinct relative face paths for the given slugs (web fonts only).
pub fn face_paths_for_slugs<'a>(slugs: impl IntoIterator<Item = &'a str>) -> Vec<&'static str> {
    let mut out = Vec::new();
    let mut seen = HashSet::new();
    for slug in slugs {
        if let Some(entry) = resolve_slug(slug) {
            if entry.system {
                continue;
            }
            for face in &entry.faces {
                if seen.insert(face.path.as_str()) {
                    out.push(face.path.as_str());
                }
            }
        }
    }
    out
}

/// Build `@font-face` rules that point at absolute CDN (or fixture) URLs.
pub fn font_face_css_remote(entry: &FontEntry, base_url: &str) -> String {
    if entry.system || entry.faces.is_empty() {
        return String::new();
    }
    let family = entry
        .family
        .as_deref()
        .unwrap_or(entry.label.as_str())
        .replace('\'', "\\'");
    let mut css = String::new();
    for face in &entry.faces {
        let url = font_asset_url(base_url, &face.path);
        css.push_str(&format!(
            "@font-face{{font-family:'{family}';font-style:normal;font-weight:{w};font-display:swap;\
unicode-range:{ur};src:url('{url}') format('woff2');}}\n",
            family = family,
            w = face.weight,
            ur = face.unicode_range,
            url = url.replace('\'', "%27"),
        ));
    }
    css
}

/// Build `@font-face` rules with `data:` URIs for the given face bytes.
///
/// `files` is keyed by catalog relative path (`files/heebo/400-latin.woff2`).
/// Missing paths are skipped (caller should fail earlier if required).
pub fn font_face_css_inline(entry: &FontEntry, files: &HashMap<String, Vec<u8>>) -> String {
    if entry.system || entry.faces.is_empty() {
        return String::new();
    }
    let family = entry
        .family
        .as_deref()
        .unwrap_or(entry.label.as_str())
        .replace('\'', "\\'");
    let mut css = String::new();
    for face in &entry.faces {
        let Some(bytes) = files.get(&face.path) else {
            continue;
        };
        let b64 = base64_encode(bytes);
        css.push_str(&format!(
            "@font-face{{font-family:'{family}';font-style:normal;font-weight:{w};font-display:swap;\
unicode-range:{ur};src:url(data:font/woff2;base64,{b64}) format('woff2');}}\n",
            family = family,
            w = face.weight,
            ur = face.unicode_range,
            b64 = b64,
        ));
    }
    css
}

fn base64_encode(bytes: &[u8]) -> String {
    // Minimal base64 without adding a crate dependency to lbl-text.
    const T: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = Vec::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let a = chunk[0] as u32;
        let b = chunk.get(1).copied().unwrap_or(0) as u32;
        let c = chunk.get(2).copied().unwrap_or(0) as u32;
        let n = (a << 16) | (b << 8) | c;
        out.push(T[((n >> 18) & 63) as usize]);
        out.push(T[((n >> 12) & 63) as usize]);
        out.push(if chunk.len() > 1 {
            T[((n >> 6) & 63) as usize]
        } else {
            b'='
        });
        out.push(if chunk.len() > 2 {
            T[(n & 63) as usize]
        } else {
            b'='
        });
    }
    String::from_utf8(out).expect("base64 alphabet is utf8")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_known_slugs() {
        assert!(resolve_slug("roboto").is_some());
        assert!(resolve_slug("Heebo").is_some());
        assert!(resolve_slug("sans").is_some());
        assert!(resolve_slug("unknown").is_none());
    }

    #[test]
    fn heebo_is_hebrew_web_font() {
        let h = resolve_slug("heebo").expect("heebo");
        assert!(!h.system);
        assert!(h.scripts.iter().any(|s| s == "hebrew"));
        assert!(!h.faces.is_empty());
    }

    #[test]
    fn remote_css_uses_base_url() {
        let h = resolve_slug("heebo").expect("heebo");
        let css = font_face_css_remote(h, "https://fonts.example/v1");
        assert!(css.contains("@font-face"));
        assert!(css.contains("https://fonts.example/v1/files/heebo/"));
        assert!(!css.contains("fonts.googleapis.com"));
    }

    #[test]
    fn catalog_has_default_base() {
        assert!(default_font_assets_base_url().starts_with("https://"));
    }
}
