<script setup lang="ts">
import { filterLabels } from "~/composables/usePreviewPayload";
import { languageForTemplateKind } from "~/utils/templateLanguage";

const { payload } = usePreviewPayload();

const filter = ref("");
const showData = ref<Record<number, boolean>>({});

const tabs = [
  { label: "Labels", icon: "i-lucide-tags", slot: "labels" as const },
  { label: "Print", icon: "i-lucide-printer", slot: "print" as const },
  { label: "Template", icon: "i-lucide-file-code-2", slot: "template" as const },
  { label: "Data", icon: "i-lucide-database", slot: "data" as const },
];

const filteredLabels = computed(() => {
  if (!payload.value) {
    return [];
  }
  return filterLabels(payload.value.labels, filter.value);
});

const dataJson = computed(() =>
  payload.value ? JSON.stringify(payload.value.data, null, 2) : "",
);

function toggleShowData(index: number, value: boolean | "indeterminate") {
  showData.value[index] = value === true;
}

function recordEntries(record: unknown): Array<[string, string]> {
  if (record == null || typeof record !== "object" || Array.isArray(record)) {
    return [["value", JSON.stringify(record)]];
  }
  return Object.entries(record as Record<string, unknown>).map(([key, value]) => [
    key,
    typeof value === "string" ? value : JSON.stringify(value),
  ]);
}
</script>

<template>
  <div v-if="!payload" class="min-h-screen flex items-center justify-center p-6">
    <UCard class="max-w-lg w-full">
      <template #header>
        <div class="font-semibold">lbl preview</div>
      </template>
      <p class="text-muted">
        No preview payload found. Open a bundle generated by
        <code class="text-sm">lbl print --protocol html</code>.
      </p>
    </UCard>
  </div>

  <div v-else class="min-h-screen bg-default">
    <UContainer class="py-6 space-y-4">
      <div class="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 class="text-2xl font-semibold">lbl preview</h1>
          <p class="text-muted text-sm">
            {{ payload.count }} label{{ payload.count === 1 ? "" : "s" }}
            <span v-if="filter.trim()">
              · showing {{ filteredLabels.length }} match{{
                filteredLabels.length === 1 ? "" : "es"
              }}
            </span>
          </p>
        </div>
      </div>

      <UTabs :items="tabs" class="w-full">
        <template #labels>
          <div class="space-y-4 pt-2">
            <UInput
              v-model="filter"
              icon="i-lucide-search"
              placeholder="Filter labels (search all data fields)…"
              class="w-full"
            />

            <div
              v-if="filteredLabels.length === 0"
              class="text-muted text-sm py-8 text-center"
            >
              No labels match this filter.
            </div>

            <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
              <UCard
                v-for="label in filteredLabels"
                :key="label.index"
                :ui="{ body: 'space-y-3' }"
              >
                <template #header>
                  <div class="flex items-center justify-between gap-3">
                    <span class="font-medium">Label #{{ label.index }}</span>
                    <UCheckbox
                      :model-value="showData[label.index] ?? false"
                      label="Show data"
                      @update:model-value="toggleShowData(label.index, $event)"
                    />
                  </div>
                </template>

                <div
                  class="rounded-md border border-default bg-[repeating-conic-gradient(#e5e7eb_0%_25%,#f3f4f6_0%_50%)] dark:bg-[repeating-conic-gradient(#1b1e25_0%_25%,#15171d_0%_50%)] bg-[length:16px_16px] p-3 flex justify-center"
                >
                  <img
                    :src="label.image"
                    :alt="`Label ${label.index}`"
                    :width="label.width"
                    :height="label.height"
                    class="max-w-full h-auto bg-white image-rendering-pixelated"
                  />
                </div>

                <div v-if="showData[label.index]" class="space-y-2">
                  <div class="text-xs font-medium text-muted uppercase tracking-wide">
                    Record data
                  </div>
                  <div class="rounded-md border border-default divide-y divide-default">
                    <div
                      v-for="[key, value] in recordEntries(label.record)"
                      :key="key"
                      class="grid grid-cols-[minmax(0,8rem)_1fr] gap-3 px-3 py-2 text-sm"
                    >
                      <span class="text-muted font-medium break-all">{{ key }}</span>
                      <span class="break-all">{{ value }}</span>
                    </div>
                  </div>
                </div>
              </UCard>
            </div>
          </div>
        </template>

        <template #print>
          <div class="mt-2 grid gap-4 lg:grid-cols-2">
            <UCard>
              <template #header>
                <span class="font-medium">Printer</span>
              </template>
              <dl class="grid gap-3 sm:grid-cols-2">
                <div>
                  <dt class="text-xs text-muted uppercase">Name</dt>
                  <dd>{{ payload.printer.name || "—" }}</dd>
                </div>
                <div>
                  <dt class="text-xs text-muted uppercase">Key</dt>
                  <dd>{{ payload.printer.key || "—" }}</dd>
                </div>
                <div>
                  <dt class="text-xs text-muted uppercase">Brand</dt>
                  <dd>{{ payload.printer.brand || "—" }}</dd>
                </div>
                <div>
                  <dt class="text-xs text-muted uppercase">Protocol</dt>
                  <dd>
                    <UBadge variant="subtle">{{ payload.printer.protocol }}</UBadge>
                  </dd>
                </div>
                <div>
                  <dt class="text-xs text-muted uppercase">DPI</dt>
                  <dd>{{ payload.printer.dpi }}</dd>
                </div>
                <div>
                  <dt class="text-xs text-muted uppercase">Max width</dt>
                  <dd>
                    {{
                      payload.printer.max_width_mm != null
                        ? `${payload.printer.max_width_mm} mm`
                        : "—"
                    }}
                  </dd>
                </div>
                <div class="sm:col-span-2">
                  <dt class="text-xs text-muted uppercase">Transport</dt>
                  <dd>{{ payload.printer.transport || "—" }}</dd>
                </div>
              </dl>
            </UCard>

            <UCard>
              <template #header>
                <span class="font-medium">Media</span>
              </template>
              <dl class="grid gap-3 sm:grid-cols-2">
                <div>
                  <dt class="text-xs text-muted uppercase">SKU</dt>
                  <dd>{{ payload.media.sku || "—" }}</dd>
                </div>
                <div>
                  <dt class="text-xs text-muted uppercase">Name</dt>
                  <dd>{{ payload.media.name || "—" }}</dd>
                </div>
                <div>
                  <dt class="text-xs text-muted uppercase">Width</dt>
                  <dd>{{ payload.media.width_mm }} mm</dd>
                </div>
                <div>
                  <dt class="text-xs text-muted uppercase">Length</dt>
                  <dd>
                    {{
                      payload.media.continuous
                        ? "Continuous"
                        : payload.media.length_mm != null
                          ? `${payload.media.length_mm} mm`
                          : "—"
                    }}
                  </dd>
                </div>
                <div>
                  <dt class="text-xs text-muted uppercase">DPI</dt>
                  <dd>{{ payload.media.dpi }}</dd>
                </div>
                <div>
                  <dt class="text-xs text-muted uppercase">Material</dt>
                  <dd>{{ payload.media.material || "—" }}</dd>
                </div>
                <div>
                  <dt class="text-xs text-muted uppercase">Color</dt>
                  <dd>{{ payload.media.color || "—" }}</dd>
                </div>
              </dl>
            </UCard>
          </div>
        </template>

        <template #template>
          <UCard class="mt-2 space-y-3">
            <dl class="grid gap-3 sm:grid-cols-2">
              <div>
                <dt class="text-xs text-muted uppercase">Kind</dt>
                <dd>{{ payload.template.kind }}</dd>
              </div>
              <div>
                <dt class="text-xs text-muted uppercase">Path</dt>
                <dd>{{ payload.template.path || "—" }}</dd>
              </div>
              <div v-if="payload.template.each" class="sm:col-span-2">
                <dt class="text-xs text-muted uppercase">Each pointer</dt>
                <dd>
                  <code>{{ payload.template.each }}</code>
                </dd>
              </div>
            </dl>
            <CodeHighlightBlock
              :content="payload.template.body"
              :language="languageForTemplateKind(payload.template.kind)"
              max-height-class="max-h-[60vh]"
            />
          </UCard>
        </template>

        <template #data>
          <UCard class="mt-2">
            <CodeHighlightBlock
              :content="dataJson"
              language="json"
              max-height-class="max-h-[70vh]"
            />
          </UCard>
        </template>
      </UTabs>
    </UContainer>
  </div>
</template>
